name: Deploy this baby to my server

on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4'
    - run: go build main.go
    - run: echo "${{ secrets.GCE_KEY }}" > key.txt
    - run: rsync -zaP -e "ssh -i key.txt" binance-price-change-go troorl@okay-boomer.ml:~/binance-price-change-go/